### ISSUE TITLE
Error: projects/{project-id}/locations/us-central1/clusters/main-cluster not found

### ISSUE THREAD

**Issue by lila** [GoogleCloudPlatform/solutions-template#32] opened 2022-12-20 22:00 UTC
i created a new solution project from the cookiecutter tool:

```
% cookiecutter https://github.com/GoogleCloudPlatform/solutions-template.git
```

this created my project, and then i followed the README instructions with the following commands:

```
 export PROJECT_ID=*** my project ***
 export ADMIN_EMAIL=*** my email ***
 export REGION=us-central1
 export API_DOMAIN=localhost
 export BASE_DIR=$(pwd)
 pwd
 gcloud auth application-default login
 gcloud auth application-default set-quota-project $PROJECT_ID
 gcloud config set project $PROJECT_ID
 curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install skaffold /usr/local/bin/
 export TF_VAR_project_id=$PROJECT_ID
 export TF_VAR_api_domain=$API_DOMAIN
 export TF_VAR_web_app_domain=$API_DOMAIN
 export TF_VAR_admin_email=$ADMIN_EMAIL
 export TF_BUCKET_NAME="${PROJECT_ID}-tfstate"
 export TF_BUCKET_LOCATION="us"
 export CURRENT_USER=$(gcloud config list account --format "value(core.account)")
 gcloud projects add-iam-policy-binding $PROJECT_ID --member="user:$CURRENT_USER" --role='roles/storage.admin'
 bash setup/setup_terraform.sh
 cd terraform/environments/dev
 terraform init -backend-config=bucket=$TF_BUCKET_NAME
 terraform apply -target=module.project_services -target=module.service_accounts -auto-approve
 terraform apply -auto-approve
```

on the last command, i get 

```
│ Error: projects/*** my project *** /locations/us-central1/clusters/main-cluster not found
│ 
│   with data.google_container_cluster.default,
│   on providers.tf line 44, in data "google_container_cluster" "default":
│   44: data "google_container_cluster" "default" {
│ 
```

any ideas?

**Comment by jonchenn** [comment] 2022-12-21 06:02
This PR resolves this bug: https://github.com/GoogleCloudPlatform/solutions-template/pull/33

**Comment by jonchenn** [comment] 2022-12-21 18:42
The PR is merged, @lila can you try again? thanks!

**Comment by lila** [comment] 2022-12-21 21:42
hi Jon,

i got past that error, but hit the following:

```
module.ingress.module.cert_manager.kubectl_manifest.cluster_issuer[0]: Creating...
╷
│ Error: letsencrypt failed to create kubernetes rest client for update of resource: Get "http://localhost/api?timeout=32s": dial tcp [::1]:80: connect: connection refused
│ 
│   with module.ingress.module.cert_manager.kubectl_manifest.cluster_issuer[0],
│   on .terraform/modules/ingress.cert_manager/main.tf line 42, in resource "kubectl_manifest" "cluster_issuer":
│   42: resource "kubectl_manifest" "cluster_issuer" {
│ 
╵
```

but i wonder if i entered in the wrong domain information.  here's what i entered:
```
% cookiecutter ./solutions-template/
project_id: *myproject*
project_name [My Project Name]: solution-one
project_short_description [My Project Description]: 
project_slug [*myproject*]: 
gcp_region [us-central1]: 
version [0.1.0]: 
admin_email [your_email@example.com]: *myemail*
api_domain [localhost]: 
web_app_domain [localhost]: 
```

what should the API_Domain and web_app_domain be set to?  localhost is probably wrong... 

k

**Comment by jonchenn** [comment] 2022-12-21 22:15
HI Karan, I'm not able to reproduce the error.

the localhost as in`api_domain` and `web_app_domain` are just placeholder for now. If you have a DNS setup, you will replace them here like:

```
api_domain [localhost]: api.example.com
web_app_domain [localhost]: web.example.com
```

Can you also try running cookiecutter directly on the remote repo?
```
cookiecutter https://github.com/GoogleCloudPlatform/solutions-template.git
```

**Comment by lavjain** [comment] 2023-01-31 19:06
`terraform/environments/dev` is not a valid configuration anymore. It has been replaced by `terraform/stages`

**Closed as completed by lavjain** 2023-01-31 19:06 UTC
Labels: bug, CI/CD
